# Generated by Django 5.2.8 on 2025-12-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='push_to_telegram',
            field=models.BooleanField(default=False, verbose_name='Отправлять в Telegram?'),
        ),
    ]
