# Generated by Django 5.2.8 on 2025-12-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_push_to_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='posted_to_socials',
        ),
        migrations.AddField(
            model_name='article',
            name='posted_to_linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='posted_to_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='posted_to_twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='promote_to_socials',
            field=models.BooleanField(default=False, verbose_name='Промо в соцсети'),
        ),
    ]
