# Generated by Django 5.2.8 on 2025-12-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_article_posted_to_socials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('TG', 'Telegram'), ('TW', 'Twitter'), ('LI', 'LinkedIn'), ('PI', 'Pinterest')], max_length=2)),
                ('scheduled_time', models.DateTimeField(verbose_name='Время публикации')),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': 'Очередь соцсетей',
                'verbose_name_plural': 'Очередь соцсетей',
                'ordering': ['scheduled_time'],
            },
        ),
    ]
