# Generated by Django 5.2.8 on 2025-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_socialqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialqueue',
            name='platform',
            field=models.CharField(choices=[('TG', 'Telegram'), ('TW', 'Twitter'), ('LI', 'LinkedIn'), ('PI', 'Pinterest'), ('FB', 'Facebook'), ('RD', 'Reddit')], max_length=2),
        ),
        migrations.AddIndex(
            model_name='socialqueue',
            index=models.Index(fields=['platform', 'scheduled_time'], name='blog_social_platfor_018102_idx'),
        ),
    ]
