# Generated by Django 5.2.8 on 2025-12-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_socialqueue_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('ARTICLE', 'Статья для сайта'), ('POST', 'Пост для соцсетей')], default='ARTICLE', max_length=10),
        ),
    ]
