# Generated by Django 5.2.8 on 2025-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='push_to_telegram',
        ),
        migrations.AddField(
            model_name='article',
            name='posted_to_pinterest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='posted_to_reddit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('ARTICLE', 'Статья для сайта'), ('POST', 'Пост для соцсетей')], default='ARTICLE', max_length=10, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='SEO Title'),
        ),
    ]
